name: Renovate

on:
  push:
    branches: [main]
    paths: 
      - renovate.json5
      - renovate.json
      - .github/renovate.json5
      - .github/renovate.json
      - .github/workflows/renovate.yml
  pull_request:
    branches: ["main"]
    paths: 
      - renovate.json5
      - renovate.json
      - .github/renovate.json5
      - .github/renovate.json
      - .github/workflows/renovate.yml

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false

      - name: Cache npm packages
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npx-renovate

      - name: Validate Renovate configuration
        run: npx --yes --package renovate -- renovate-config-validator
