name: Renovate

on:
  push:
    branches: [main]
    paths: 
      - renovate.json5
      - renovate.json
      - .github/renovate.json5
      - .github/renovate.json
      - .github/workflows/renovate.yml
  pull_request:
    branches: ["main"]
    paths: 
      - renovate.json5
      - renovate.json
      - .github/renovate.json5
      - .github/renovate.json
      - .github/workflows/renovate.yml

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Cache npm packages
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npx-renovate

      - name: Validate Renovate configuration
        run: npx --yes --package renovate -- renovate-config-validator
