name: Zizmor

on:
  push:
    branches: [main]
    paths: ['.github/workflows/**']
  pull_request:
    branches: [main]
    paths: ['.github/workflows/**']

permissions:
  contents: read

jobs:
  zizmor:
    name: Audit
    runs-on: ubuntu-latest  # requires Docker, cannot use ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@c2c887f84674f9c15123e2905d2d307675d8bc01
        with:
          advanced-security: false
          annotations: true
