name: Zizmor

on:
  push:
    branches: [main]
    paths: ['.github/workflows/**']
  pull_request:
    branches: [main]
    paths: ['.github/workflows/**']

permissions:
  contents: read

jobs:
  zizmor:
    name: Audit
    runs-on: ubuntu-latest  # requires Docker, cannot use ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@7462f075f718787753331c6d98ca9ef8eb41e735
        with:
          advanced-security: false
          annotations: true
