name: Zizmor

on:
  push:
    branches: [main]
    paths: ['.github/workflows/**']
  pull_request:
    branches: [main]
    paths: ['.github/workflows/**']

permissions:
  contents: read

jobs:
  zizmor:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Run zizmor
        uses: woodruffw/zizmor-action@v1
        with:
          advanced-security: false
          annotations: true
